-- This migration is a NO-OP to resolve duplicate Session table creation.
--
-- CONTEXT:
-- Migration 20260215202040_add_sessions already created the Session table
-- with the authoritative schema (userId/orgId-based).
-- This migration originally attempted to create Session again with a
-- different workerId-based schema, which would fail on fresh database setup.
--
-- RESOLUTION:
-- Neutralized by converting to no-op. Subsequent migrations continue to
-- build upon the authoritative Session table from 20260215202040_add_sessions.
-- This file is retained to preserve migration history and avoid migration
-- number conflicts.

-- No operations performed (duplicate migration neutralized)
