import type { ClaudeMessageRequest, ClaudeMessageResponse } from '../contracts/claudeConfig';

type FetchLike = typeof fetch;

export class ClaudeClient {
  private readonly apiKey: string;
  private readonly fetchImpl: FetchLike;

  constructor(params: { apiKey: string; fetchImpl?: FetchLike }) {
    this.apiKey = params.apiKey;
    this.fetchImpl = params.fetchImpl ?? fetch;
  }

  async createMessage(req: ClaudeMessageRequest): Promise<ClaudeMessageResponse> {
    try {
      const res = await this.fetchImpl('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'x-api-key': this.apiKey,
          'anthropic-version': '2023-06-01',
        },
        body: JSON.stringify({
          model: req.model ?? 'claude-3-5-sonnet-20241022',
          max_tokens: req.maxTokens ?? 1024,
          temperature: req.temperature ?? 0,
          system: req.system ?? undefined,
          messages: [{ role: 'user', content: req.userText }],
        }),
      });

      const json = await res.json().catch(() => null);
      if (!res.ok) {
        const msg = typeof json?.error?.message === 'string' ? json.error.message : `Anthropic HTTP ${res.status}`;
        throw new Error(msg);
      }

      const model = typeof json?.model === 'string' ? json.model : (req.model ?? 'unknown');
      const text = Array.isArray(json?.content) ? String(json.content?.[0]?.text ?? '') : '';
      const inputTokens = typeof json?.usage?.input_tokens === 'number' ? json.usage.input_tokens : null;
      const outputTokens = typeof json?.usage?.output_tokens === 'number' ? json.usage.output_tokens : null;

      // requestId is now generated by caller (UsageAuditService uses DB id); keep stable output shape.
      return { requestId: 'n/a', model, text, inputTokens, outputTokens };
    } catch (err) {
      throw err;
    }
  }
}
